/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant;

/**
 *
 * @author mallikang.2015
 */
public class Restaurant extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant
     */
    public Restaurant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        waiterLabel = new javax.swing.JLabel();
        chefsLabel = new javax.swing.JLabel();
        seatingLabel = new javax.swing.JLabel();
        increaseChefs = new javax.swing.JButton();
        decreaseWaiters = new javax.swing.JButton();
        increaseWaiters = new javax.swing.JButton();
        decreaseChefs = new javax.swing.JButton();
        decreaseSeating = new javax.swing.JButton();
        increaseSeating = new javax.swing.JButton();
        numWaiters = new javax.swing.JTextField();
        numChefs = new javax.swing.JTextField();
        numSeating = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(160, 136, 195));
        setForeground(new java.awt.Color(160, 136, 255));

        menu.setBackground(new java.awt.Color(125, 177, 177));

        waiterLabel.setText("Waiters");

        chefsLabel.setText("Chefs");

        seatingLabel.setText("Seating");

        increaseChefs.setText("+");
        increaseChefs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseChefsActionPerformed(evt);
            }
        });

        decreaseWaiters.setText("-");
        decreaseWaiters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseWaitersActionPerformed(evt);
            }
        });

        increaseWaiters.setText("+");
        increaseWaiters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseWaitersActionPerformed(evt);
            }
        });

        decreaseChefs.setText("-");
        decreaseChefs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseChefsActionPerformed(evt);
            }
        });

        decreaseSeating.setText("-");
        decreaseSeating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseSeatingActionPerformed(evt);
            }
        });

        increaseSeating.setText("+");
        increaseSeating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseSeatingActionPerformed(evt);
            }
        });

        numWaiters.setText("1");
        numWaiters.setToolTipText("");

        numChefs.setText("2");
        numChefs.setToolTipText("");

        numSeating.setText("5");
        numSeating.setToolTipText("");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(waiterLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numWaiters, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(increaseWaiters)
                        .addGap(7, 7, 7)
                        .addComponent(decreaseWaiters)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(increaseChefs)
                        .addGap(6, 6, 6)
                        .addComponent(decreaseChefs))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(chefsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numChefs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(314, 314, 314)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(increaseSeating)
                        .addGap(5, 5, 5)
                        .addComponent(decreaseSeating))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(seatingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numSeating, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waiterLabel)
                    .addComponent(seatingLabel)
                    .addComponent(chefsLabel)
                    .addComponent(numWaiters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numChefs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numSeating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(increaseChefs)
                    .addComponent(increaseWaiters)
                    .addComponent(decreaseWaiters)
                    .addComponent(decreaseChefs)
                    .addComponent(decreaseSeating)
                    .addComponent(increaseSeating))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(241, 111, 81));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void increaseChefsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseChefsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_increaseChefsActionPerformed

    private void decreaseWaitersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseWaitersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decreaseWaitersActionPerformed

    private void increaseWaitersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseWaitersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_increaseWaitersActionPerformed

    private void decreaseChefsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseChefsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decreaseChefsActionPerformed

    private void decreaseSeatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseSeatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decreaseSeatingActionPerformed

    private void increaseSeatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseSeatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_increaseSeatingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chefsLabel;
    private javax.swing.JButton decreaseChefs;
    private javax.swing.JButton decreaseSeating;
    private javax.swing.JButton decreaseWaiters;
    private javax.swing.JButton increaseChefs;
    private javax.swing.JButton increaseSeating;
    private javax.swing.JButton increaseWaiters;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField numChefs;
    private javax.swing.JTextField numSeating;
    private javax.swing.JTextField numWaiters;
    private javax.swing.JLabel seatingLabel;
    private javax.swing.JLabel waiterLabel;
    // End of variables declaration//GEN-END:variables
}
